- name: Desplegar entorno del laboratorio Watch
  hosts: ibmi
  gather_facts: no
  tasks:

    - name: Crear carpeta temporal si no existe
      ansible.builtin.file:
        path: /tmp/ibmi-watch
        state: directory

    - name: Descomprimir el SAVF ZIP
      ansible.builtin.unarchive:
        src: ../savf/wchpgmlab.savf.zip
        dest: /tmp/ibmi-watch
        remote_src: false

    - name: Copiar SAVF al sistema IBM i
      shell: |
        system "CPYFRMSTMF FROMSTMF('/tmp/ibmi-watch/wchpgmlab.savf') TOMBR('/qsys.lib/misavfs.lib/wchpgmlab.file')"

    - name: Restaurar objeto desde SAVF
      shell: |
        system "RSTOBJ OBJ(WCHPGMLAB) SAVLIB(OBUSTOS) DEV(*SAVF) SAVF(MISAVFS/WCHPGMLAB)"

    - name: Verificar watches activos existentes
      shell: |
        db2 "SELECT * FROM QSYS2.WATCH_INFO WHERE WATCH_SESSION_TYPE = '*STRWCH'"
      register: watch_output

    - name: Mostrar resultado de WATCH_INFO
      debug:
        msg: "{{ watch_output.stdout_lines }}"

    - name: Validar privilegios de funciones de servicio WATCH
      shell: |
        DSPFNCUSG FNCID(QIBM_SERVICE_WATCH) USRPRF({{ ansible_user }})
        DSPFNCUSG FNCID(QIBM_WATCH_ANY_JOB) USRPRF({{ ansible_user }})

    - name: Validar autorización al comando STRWCH
      shell: |
        DSPOBJAUT OBJ(QSYS/STRWCH) OBJTYPE(*CMD)

    - name: Validar autorización al comando ENDWCH
      shell: |
        DSPOBJAUT OBJ(QSYS/ENDWCH) OBJTYPE(*CMD)
