name: Desplegar entorno del laboratorio Watch
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Crear carpeta temporal si no existe
      ansible.builtin.file:
        path: "~"
        state: directory

    - name: Eliminar archivo previo si existe
      ansible.builtin.file:
        path: ~/watch.savf
        state: absent

    - name: Descomprimir el SAVF ZIP
      ansible.builtin.unarchive:
        src: ~/ansible/IBMIADM_Lab04e/savf/watch.zip
        dest: "/"
      register: unzip
    
#    - name: Debug
#      debug:
#        msg: "{{ unzip }}"

    - name: Elevar privilegios temporalmente usando db2util
      shell: |
        /QOpenSys/pkgs/bin/db2util "CALL LABADM.ELEVATE2(2)"

# Realizar las sustituciones correspondientes
    - name: Copiar SAVF desde IFS a QSYS usando CL
      ibm.power_ibmi.ibmi_cl_command:
        cmd: "CPYFRMSTMF FROMSTMF('/home/IBMIADM00/watch.savf') TOMBR('/QSYS.LIB/IBMIADM00.LIB/WATCH.FILE') MBROPT(*REPLACE)"

# Realizar las sustituciones correspondientes
    - name: Restaurar objeto desde SAVF con módulo
      ibm.power_ibmi.ibmi_object_restore:
        object_names: WCHPGMLAB
        object_types: '*PGM'
        object_lib: QTEMP
        parameters: "RSTLIB(IBMIADM00)"
        savefile_lib: IBMIADM00
        savefile_name: WATCH

    - name: Verificar watches activos existentes
      ibm.power_ibmi.ibmi_sql_query:
        sql: "SELECT * FROM QSYS2.WATCH_INFO WHERE WATCH_SESSION_TYPE = '*STRWCH'"
      register: watch_output

    - name: Verificar autoridad al comando STRWCH - ARRANCAR OBSERVACIÓN
      ibm.power_ibmi.ibmi_object_authority:
        operation: display
        object_name: STRWCH
        object_library: QSYS
        object_type: '*CMD'
      register: auth_strwch

    - name: Verificar autoridad al comando ENDWCH - FINALIZAR OBSERVACIÓN
      ibm.power_ibmi.ibmi_object_authority:
        operation: display
        object_name: ENDWCH
        object_type: '*CMD'
        object_library: QSYS
      register: auth_endwch

    - name: Verificar autoridad al programa QSCRWCHL - RETRIEVE WATCHES LIST
      ibm.power_ibmi.ibmi_object_authority:
        operation: display
        object_name: QSCRWCHL
        object_type: '*PGM'
        object_library: QSYS
      register: auth_QSCRWCHL

    - name: Verificar autoridad al programa QSCRWCHI - RETRIEVE INFORMATION ON WATCH SESSION ACTIVE
      ibm.power_ibmi.ibmi_object_authority:
        operation: display
        object_name: QSCRWCHI
        object_type: '*PGM'
        object_library: QSYS
      register: auth_QSCRWCHI
    
    - name: Valida permisos
      ibm.power_ibmi.ibmi_sql_query:
        sql: >-
          Select object_schema, object_name, object_type, authorization_name, object_authority, 
          object_operational, object_alter, data_read, data_execute, text_description
          From qsys2.object_privileges
          Where name = 'STRWCH' And object_schema = 'QSYS' And object_type = '*CMD' And
          authorization_name Like '%IBMIADM%'
      register: sql_strwch

    - name: Debug
      debug:
        msg: 
          "{{ sql_strwch.row[0] }}"

    - name: Debug
      debug:
        msg: 
        - "OBJECT_NAME : {{ auth_strwch.object_authority_list[0].OBJECT_NAME }}"
        - "OBJECT_AUTHORITY : {{ auth_strwch.object_authority_list[0].OBJECT_AUTHORITY }}"
        - "OBJECT_NAME : {{ auth_endwch.object_authority_list[0].OBJECT_NAME }}"
        - "OBJECT_AUTHORITY : {{ auth_endwch.object_authority_list[0].OBJECT_AUTHORITY }}"
        - "OBJECT_NAME : {{ auth_QSCRWCHL.object_authority_list[0].OBJECT_NAME }}"
        - "OBJECT_AUTHORITY : {{ auth_QSCRWCHL.object_authority_list[0].OBJECT_AUTHORITY }}"
